### ISSUE TITLE
802.1q interface

### ISSUE THREAD

**Issue by jmpolom** [dentproject/dentOS#108]
iproute2 and ifupdown2 support to enable configuring 802.1q interfaces

*Planned for "Beeblebrox" release*

**Comment by jmpolom** [comment]
There was a comment during the TSC call on 22 September that suggested the Marvell Prestera switchdev driver doesn't support "VLAN netdevs" or something to that effect if I recall correctly. I've created an [issue on the switchdev-prestera repo](https://github.com/Marvell-switching/switchdev-prestera/issues/6) to seek some clarity on this because the current documentation is outdated (1+ year old) and pretty sparse.

The mlxsw driver seems to support VLAN sub-devices but doesn't show a full configuration to include adding an IP address to a VLAN sub-device. This should be tested on a supported platform that uses mlxsw.

**Comment by taraschornyiplv** [comment]
vlan sub-interface can be created only on top of .1q bridge 
https://github.com/Marvell-switching/switchdev-prestera/wiki/l3-configuration#1q-bridge-example
