### ISSUE TITLE
QoS mapping

### ISSUE THREAD

**Issue by jmpolom** [dentproject/dentOS#112]
QoS maps should be configurable (dscp-intp, cos-intp, intp-queue). Also need an option to configure DSCP/CoS trust.

**Comment by Mickey201** [comment]
Marvell Prestera Switchdev driver will support QoS as part of the DENT 3.0 release.

**Comment by taraschornyiplv** [comment]
https://github.com/Marvell-switching/switchdev-prestera/wiki/QoS#priority-assignment
