### ISSUE TITLE
Hardware Acceleration for NAT-44 

### ISSUE THREAD

**Issue by jmpolom** [dentproject/dentOS#113]
Static and Dynamic NAT 46/44 and Port Translation

**Comment by sonoble** [comment]
Currently only NAT44 has been implemented

**Comment by jmpolom** [comment]
The original comment and title on this issue mentions port translation which is a mistake. That should be __prefix__ translation for IPv6 since that is the stateless analog to stateful NAT44, NAT46 and NAT66. Unfortunately, IPv6 NPT is unavailable with `nftables`.

Luckily at the moment dentOS is quite behind here and still on `iptables` however future moves that should include a planned migration to `nftables` means npt will likely become unavailable due to lack of upstream support.

**Comment by taraschornyiplv** [comment]
Nat 44 support documentation https://github.com/Marvell-switching/switchdev-prestera/wiki/NAT-Stateful
