### ISSUE TITLE
802.1x dataplane support

### ISSUE THREAD

**Issue by jmpolom** [dentproject/dentOS#116]
Need to test and mockup Prestera `tc filter` rule to determine if it can trap EAP to the CPU. This [may be supported](https://github.com/Marvell-switching/switchdev-prestera/wiki/supported-actions,-keys-and-rules) per Prestera wiki.

**Comment by taraschornyiplv** [comment]
prestera switchdev driver do support bridge locked port attribute

from prestera [wiki](https://github.com/Marvell-switching/switchdev-prestera/wiki/Bridge-and-VLAN)
> Bridge port locked – a port that is not a subject to flooding unknown (UC, MC) traffic, nor to an automatic learning when locked.
Locked port forwards only mac-authorized traffic (SA MAC address is persistent in the FDB - user should add a static FDB entry, which is treated as mac-auth entry).
In case if there's no mac-authorized entries in the FDB, port's only capable of trapping the PAE (802.1x) packets.
