### ISSUE TITLE
IGMP Snooping

### ISSUE THREAD

**Issue by jmpolom** [dentproject/dentOS#128]
Support IGMP Snooping to filter unwanted broadcast/multicast in a l2 domain. Only multicast to ports in a vlan that are interested in multicast traffic.

**Comment by Mickey201** [comment]
Marvell Prestear Switchdev driver targetted to support IGMP as part of the Release-C.

**Comment by taraschornyiplv** [comment]
https://github.com/Marvell-switching/switchdev-prestera/wiki/IGMP-Snooping-MDB
