### ISSUE TITLE
POE Controller

### ISSUE THREAD

**Issue by jmpolom** [dentproject/dentOS#132]
Implement and integrate [POE controller software](https://github.com/dentproject/poed) into DENT

**Comment by snobleaws** [comment]
Need list of supported hardware, documentation and determine if this is included by default or available to be installed in dentOS.

**Comment by jmpolom** [comment]
@snobleaws there are a couple lingering action items from the Feature Working Group where:

1. Delta was going to supply PoE controller software specifications
2. Amazon was going to look into supplying PoE daemon requirements

I would agree that some documentation is necessary here because long term the best plan is probably to look into engagement the kernel community to get PoE control upstreamed. If Linux on access switches is to be a big thing it makes sense to look at upstreaming things here.

**Comment by lperkov** [comment]
@paulmenzel unfortunately it is still not public here on GitHub. @snobleaws please advise on this.

**Comment by jmpolom** [comment]
Who from Delta can this issue be assigned to? Discussions had indicated both Delta and Amazon could supply something to help push this issue towards a resolution.

**Comment by jluebbe** [comment]
> Nice. Where can the code for the POE daemon be found?

@paulmenzel It seems the poe daemon is public now: https://github.com/dentproject/poed/tree/main/dentos-poe-agent/opt/poeagent

**Comment by jluebbe** [comment]
From a high-level perspective, does the poe-agent implementation cover all requirements? Otherwise, what is still missing?

**Comment by taraschornyiplv** [comment]
poed is used as PoE management daemon 
https://github.com/dentproject/poed/blob/main/dentos-poe-agent/opt/poeagent/docs/Userguide
