### ISSUE TITLE
Missing packages in the DENT community images

### ISSUE THREAD

**Issue by taskin-ucpinar** [dentproject/dentOS#134]
Based on the discussion we had during the TCS, we are missing the following packages in the DENT images.
-	dbus-user-session
-	python3-pyroute2
-	auditd
-	libcap2-bin
-	python-pip

**Comment by paulmenzel** [comment]
Typo: *pthon3-pyroute2* → *python3-pyroute2*

**Comment by paulmenzel** [comment]
1.  What do you need these for? For example *auditd*?
2.  Do you need special versions, or are the one in the official Debian 8 (stretch) archives fine?

**Comment by paulmenzel** [comment]
Other typo: *libcab2-bin* → *libcap2-bin*

**Comment by taskin-ucpinar** [comment]
Fixed the typos.

I do not know what auditd is used for. Amazon's internal DENT version includes it.
Steve, do you have any version dependency on these packages, or would the latest versions be OK?

**Comment by jmpolom** [comment]
Suggest that you tag @sonoble to get his attention on this matter.

**Comment by sonoble** [comment]
There is no reason to have auditd in dentOS as it is not used by any of the tools currently.

**Comment by taraschornyiplv** [comment]
dbus package has been added #138
