### ISSUE TITLE
Celestica redstone xp support?

### ISSUE THREAD

**Issue by bentwire** [dentproject/dentOS#136]
What would be required to add this back in?  I have 2 of these and would really like to get a NOS running on them :)

**Comment by paulmenzel** [comment]
What are the device specifications? If the ASIC is supported by Linux’ switchdev, then it should be doable. Otherwise, unless the ASIC vendor adds switchdev support, there is no chance to get it added back.

**Comment by bentwire** [comment]
Its a broadcom tritan 2.  I think it's still supported by then.

**Comment by paulmenzel** [comment]
Broadcom does not support switchdev, so currently it’s possible to add the device to dentOS. Please contact Broadcom to show demand for that, but until then, please close the issue.

**Comment by bentwire** [comment]
Ahh well damn.  I doubt they would for an older switch like this one.  Thanks for the reply!
