### ISSUE TITLE
Prestera driver documentation update

### ISSUE THREAD

**Issue by jmpolom** [dentproject/dentOS#137]
The current documentation for the [switchdev-prestera driver](https://github.com/Marvell-switching/switchdev-prestera/wiki) is over a year old. New features have been added to this driver which are undocumented. These docs require an update for basic usability.

cc: @trishan @sonoble @taraschornyiplv @Mickey201

**Comment by Mickey201** [comment]
All Marvell DOCs were updated on Feb 2022.
Additional comments will be most appreciated.
