### ISSUE TITLE
[info request] dent configuration documentation 

### ISSUE THREAD

**Issue by ByReaL** [dentproject/dentOS#168]
can anyone point me where is the dent documentation how to configure each feature.
for example how you configure bgp in dent 
how do you configure an ip on a interface
how do you configure L1 settings 
....
is there a dent user manual for configuration (dent docs not 3rd party docs) similar with 
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/92x/vxlan-92x/configuration/guide/b-cisco-nexus-9000-series-nx-os-vxlan-configuration-guide-92x/b_Cisco_Nexus_9000_Series_NX-OS_VXLAN_Configuration_Guide_9x_chapter_010000.html

**Comment by Mickey201** [comment]
Hi, the DENT command line is based on the Linux native utilities like 'ip', 'ethtool' etc.
There are many references on the WEB that shows these examples.
For quick reference that assures the supported features + examples: please approach the Marvell Switchdev wiki page.
https://github.com/Marvell-switching/switchdev-prestera/wiki
