### ISSUE TITLE
tc persistency 

### ISSUE THREAD

**Issue by taraschornyiplv** [dentproject/dentOS#182]
**Overview**
Support to save and restore tc rules configuration 

**Use Case**
allow to save and restore tc configuration after reboot

**Comment by paulmenzel** [comment]
How are tc rules currently configured?

**Comment by paulmenzel** [comment]
> At this moment tc configuration is runtime only

Yes, I understood that.

So, currently, every user executes `tc` commands.

To make this persistent, all they have to do, is put these commands in a script, and create a systemd service executing the script? (Or write the `tc` commands directly as `ExecStart=` lines into the script.)

Is that, what you want?

**Comment by taraschornyiplv** [comment]
> > At this moment tc configuration is runtime only
> 
> Yes, I understood that.
> 
> So, currently, every user executes `tc` commands.
> 
> To make this persistent, all they have to do, is put these commands in a script, and create a systemd service executing the script? (Or write the `tc` commands directly as `ExecStart=` lines into the script.)
> 
> Is that, what you want?

no. the idea is to have behavior similar to iptables-save.

**Comment by paulmenzel** [comment]
> no. the idea is to have behavior similar to iptables-save.

Is it already possible to dump the traffic control state, and just needs to be integrated into dentOS?

> > [systemd.network](https://www.freedesktop.org/software/systemd/man/systemd.network.html) also has some options [to configure a subset](https://www.freedesktop.org/software/systemd/man/systemd.network.html#%5BCAKE%5D%20Section%20Options)
> > I think you should elaborate on the usecase.
> 
> this looks interesting. however, I see it only supports tc-cake and not tc-flower

No idea. I guess support could be easily added to systemd though, it it’s clear what is wanted.

Again, please update the issue description with your use cases.

**Comment by taraschornyiplv** [comment]
there is a Petunia https://github.com/dentproject/petunia which implements this. @snobleaws @sonoble can we have more info about it.
this feature request is created to have a track record about petunia

**Comment by paulmenzel** [comment]
What commit fixed the issue?
