### ISSUE TITLE
LLDP TLV for type 3 and type 4 extension

### ISSUE THREAD

**Issue by d1115choi** [dentproject/dentOS#193]
Hello LLDP folks,

I use 1.0.15 lldp stable version. From the source code, I built/run the image on Ubuntu LTS 14.04.

With the lldpcli, I can generate LLDPDU including "Ieee 802.3 - Power Via MDI" TLV, whose TLV type=127.
This TLV includes TLV header, basic field, DLL classification extention but not type 3 and type 4 extension with the command below:
lldpcli configure dot3 power pd supported enabled powerpairs spare class class-3 type 1 source pse priority low requested 10000 allocated 15000

I am wondering how I can generate LLDPDU including the type 3 and type 4 extention.
Additionally, if LLDPDU does not include the type 3 and type 4 extention" for type 3 or 4, do we violate the standard? 

Any help will be highly appreciated.

Regards,
David Choi

**Comment by paulmenzel** [comment]
Dear @d1115choi, you created this issue in the dentOS project. Did you want to contact the [lldpd project](https://lldpd.github.io/), which also has an [issue tracker](https://github.com/lldpd/lldpd/issues) (currently at GitHub). Kind regards, Paul

**Comment by d1115choi** [comment]
Thank you Paulmenzel.
