### ISSUE TITLE
dhcp address not requested from dhcp server after reboot

### ISSUE THREAD

**Issue by vikumarks** [dentproject/dentOS#207]
After upgrading the DENT OS build (DENT OS DENTOS-HEAD, 2023-03-13.08:50-c9fc890) , dhcp address not requested from dhcp server after reboot

The /etc/network/interfaces is missing below lines .
`# The management interface
auto ma1
iface ma1 inet dhcp
`

**Comment by taraschornyiplv** [comment]
this issue is fixed by #186 
please try this build:
https://repos.refinery.dev/repository/dent/snapshots/org/dent/dentos/DENTOS-HEAD_ONL-OS9_2023-03-14.0522-f6d2dff_ARM64_INSTALLED_INSTALLER

**Comment by vikumarks** [comment]
Works; Verified in DENTOS-HEAD, 2023-03-15.05:23-f6d2dff
