### ISSUE TITLE
ONL seems archived

### ISSUE THREAD

**Issue by ferrywu** [dentproject/dentOS#221]
https://github.com/opencomputeproject/OpenNetworkLinux/commit/38d4baa8c75e9cd154aaf707eb6e86cb9396b5a2
According to the commit, ONL seems archived
Will DentOS project continue even if ONL is archived ?

**Comment by taraschornyiplv** [comment]
Hi @ferrywu. DentOS project will continue even if ONL is archived.

**Comment by williamcola7** [comment]
Does DentOS project cover all functions of ONL, such as DCSG ( Disaggregated Cell Site Gateway )?

**Comment by taraschornyiplv** [comment]
> Does DentOS project also support DCSG ( Disaggregated Cell Site Gateway) device?

As of now, detntOS does not support this device. 
List od supported hardware can be found here:
https://github.com/dentproject/dentOS/wiki/Supported-Hardware

**Comment by williamcola7** [comment]
> > Does DentOS project also support DCSG ( Disaggregated Cell Site Gateway) device?
> 
> As of now, detntOS does not support this device. List of supported hardware can be found here: > 
> https://github.com/dentproject/dentOS/wiki/Supported-Hardware

Hi [taraschornyiplv](https://github.com/taraschornyiplv) ,
Since DentOS comes from ONL, 
does DentOS include DCSG feature as ONL?
I would like to know whether users or partners could use DentOS to develop DCSG feature on their own DCSG hardware?

**Comment by taraschornyiplv** [comment]
DentOS do support ONL features. @williamcola7  Can you please specify which DCSG feature you are referring?
I do believe that users or companies can use DentOS to develop DCSG feature on their own DCSG hardware.

if you have a feature request I'd recommend you join the next Feature Working group meeting on Thu Jun 8th at  8 am PST where we discuss the new features and roadmap for DentOS. Link to register: https://zoom.us/meeting/register/tJUtf-msrjIjE9ZUzH0SXLnrf3DzCel6xI07

**Comment by williamcola7** [comment]
Hi [taraschornyiplv](https://github.com/taraschornyiplv) ,
SAI is put into the feature list of dentos roadmap, but I cannot get a specific schedule from the roadmap.
Do you know DentOS has any futher plan to support it?
Does it mean BCM switch will be supported in the future? 

(The roadmap comes from DentOS website: https://dent.dev/dentos/)
![image](https://github.com/dentproject/dentOS/assets/3837736/472c7148-7534-4afd-9825-66f5dc7b3f96)

**Comment by taraschornyiplv** [comment]
@williamcola7 Yes DentOS will support SAI as an additional interface to HW.  Supporting SAI means that any SAI-enabled switch can be supported. 
Schedule for SAI to be finalized.
