### ISSUE TITLE
FRR - Static route Next hop change is not tracked

### ISSUE THREAD

**Issue by sandnaga** [dentproject/dentOS#24]
Fix is here: [https://github.com/FRRouting/frr/pull/4602](url)

**Comment by paulmenzel** [comment]
(The URL behind the link points to https://github.com/dentproject/dentOS/issues/url. Can you edit your message, or is that a GitHub issue?

**Comment by paulmenzel** [comment]
https://github.com/FRRouting/frr/pull/4602

**Comment by taraschornyiplv** [comment]
@sandnaga do you see this issue in latest release?

**Comment by sandnaga** [comment]
We have not integrated the 3.x release yet. I have seen the issue with
static route next hop change in FRR needing restart, will update when we
have test results.
Is this something urgent?

**Comment by taraschornyiplv** [comment]
it is not urgent.

**Comment by sandnaga** [comment]
Ok. Thanks.

**Comment by KanjiMonster** [comment]
Since the latest DentOS release includes a FRR version that has the mentioned fix, I'll close the issue.
