### ISSUE TITLE
MZ package update

### ISSUE THREAD

**Issue by daniellerts** [dentproject/dentOS#68]
Package is too old and causes failures in our workflow with DNI TX4810 using Debian 9.
Please update:
- mausezahn: 0.6.2>0.6.7

Thanks!

**Comment by paulmenzel** [comment]
What failures are seeing? Could you please open a separate issue for *lldpad*?

**Comment by daniellerts** [comment]
The current version doesn't support either raw hex string , or -R to set packet priority in the MZ command line.

Created a new ticket for lldpad with it issues.

**Comment by paulmenzel** [comment]
Thanks.

[The package name is *netsniff-ng*.](https://packages.debian.org/netsniff-ng) (There is also a [package *mz*](https://packages.debian.org/mz), which seems outdated.)

**Comment by daniellerts** [comment]
Yes i need netsniff-ng to be updated, right.

**Comment by sonoble** [comment]
Will investigate

**Comment by KanjiMonster** [comment]
DentOS updated to debian 10 now provides 0.40, which should hopefully be new enough.

```
root@localhost:~# apt-cache show mz
Package: mz
Source: mz (0.40-1.1)
Version: 0.40-1.1+b1
```
