### ISSUE TITLE
lldpad package update

### ISSUE THREAD

**Issue by daniellerts** [dentproject/dentOS#69]
Package is too old and causes failures in our workflow with DNI TX4810 using Debian 9.
Please update:
- lldpad: v0.9.46> v1.0.1

Thanks!

**Comment by daniellerts** [comment]
The problem is that we are missing the patch: https://github.com/intel/openlldp/pull/9
which is included in the new version of lldpad and its absence causes lack of support the selector 5.

**Comment by sonoble** [comment]
Will look into updating

**Comment by KanjiMonster** [comment]
With the update to Debian 10 lldpad 1.0.1 is now available.

```
root@localhost:~# apt-cache show lldpad
Package: lldpad
Version: 1.0.1+git20180808.4e642bd-1
```

A quick look at the [debian sources](http://deb.debian.org/debian/pool/main/l/lldpad/lldpad_1.0.1+git20180808.4e642bd.orig.tar.gz) shows that the changes from https://github.com/intel/openlldp/pull/9 are included in the binary.
