### ISSUE TITLE
Proposed "new feature" issue template

### ISSUE THREAD

**Issue by jmpolom** [dentproject/dentOS#89]
The DENT project should have an issue template that will populate in new feature request issues. This should help ensure requesters submit sufficient information to start a discussion thread that can shape requirements sufficiently enough to begin feature development.

> # New feature template
> 
> ## Overview
> Describe the feature and what it should do. This should be at least one sentence and may be several. Preferably, this is not a bullet point list but rather a verbose description of the thing.
> 
> ## Use Case
> Succinctly describe how the feature will be used. Providing a sense of scale (instances of this feature) and performance requirements would be helpful. One or two sentences should be adequate.
>
> ## Operation
> * List how the feature works. Include details such as what packages are required, packet types are manipulated, etc. if such details are known.
> * Describe how the user interacts with the feature and if userspace tool development seems necessary.
> * Optionally, provide some high level insight on how the feature may be implemented
>
> ## Testing
> Optionally, explain how this feature could be tested, what a preferred test method may be or who will write the test case.
>
> ## Sponsoring organization
> Provide the name of the organization(s) that will be developing the feature or a portion of it.

**Comment by jwagantall** [comment]
I pushed an initial change here: https://github.com/dentproject/dentOS/commit/c82dbd6e0fe33d00f921ea419d104b9f8dd09300

Let me know if you have permissions to propose changes to this file. 

New changes to this template will need to be done via PR against this branch for which you will need to have committer permissions. 

If you have any permissions issues, please let us know via http://support.linuxfoundation.org/

**Comment by jmpolom** [comment]
It looks like this change has made it so the only new issue type is a feature request. I think we need to create another template to enable a bug report or other/general issue type.

@jwagantall which workflow did you use to create this template? It seems directly creating a template file in `.github/ISSUE_TEMPLATE` method is the older method and a newer method is available through the repo “Settings” page which I cannot see since I’m not an admin on this repo. It kind of seems like they both work similarly though since both result in a commit to the repo.

Issue template documentation: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

@sonoble this should be on the agenda for the TSC meeting next week. This project needs issue templates for bugs and general issue types. We could generalize the feature request template or create separate ones. Might as well also talk PR template too. I know we have discussed all of these items during previous Feature Working Group meetings.

**Comment by jmpolom** [comment]
@jwagantall added the new feature template which is acceptable closure criteria for this issue.
