### ISSUE TITLE
MAC Authentication Bypass (802.1x)

### ISSUE THREAD

**Issue by jmpolom** [dentproject/dentOS#97]
Feature purposed to authenticate connected devices in a L2-network similar to 802.1x, but using device's MAC-address instead of EAP messages. New MAC-address should be trapped to CPU and delivered to RADIUS-server for authentication with 2 outcomes:
 * Accept:
   * MAC/port is associated with the VLAN specified by RADIUS-server
 * Reject:
   * MAC is prohibited and filtered from trapping/authentication for a period of time
   * MAC is associated with a preconfigured guest VLAN

**Comment by taraschornyiplv** [comment]
https://github.com/Marvell-switching/switchdev-prestera/wiki/bridge-and-vlan#bridge-port-configurations
